site_name: Eevee Chat
site_description: A unified chat UI for multiple LLMs
site_long_description: Eevee is a unified and simple chat UI for working with multiple LLM frameworks in one place.
site_author: Shaked Zychlinski
site_url: http://shakedzy.xyz/eevee-chat/
repo_name: shakedzy/eevee-chat
repo_url: https://github.com/shakedzy/eevee-chat
copyright: Copyright &copy; Shaked Zychlinski
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode 
  logo: images/favicon.png
  favicon: images/favicon.png
nav:
  - Home: 'index.md'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
plugins:
  - search
extra:
  social:
    - icon: material/web
      link: https://shakedzy.xyz/
    - icon: fontawesome/brands/github
      link: https://github.com/shakedzy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shakedzy/
    - icon: fontawesome/brands/medium
      link: https://shakedzy.medium.com/