[models]
openai = [
    'GPT-4 Turbo::gpt-4-turbo-preview', 
    'GPT-4::gpt-4', 
    'GPT-3.5 Turbo::gpt-3.5-turbo'
    ]
anthropic = [
    'Claude 3 Opus::claude-3-opus-20240229', 
    'Claude 3 Sonnet::claude-3-sonnet-20240229', 
    'Claude 3 Haiku::claude-3-haiku-20240307'
    ]
mistral = [
    'Large::mistral-large-latest', 
    'Medium::mistral-medium-latest', 
    'Small::mistral-small-latest'
    ]
deepseek = [
    'Chat::deepseek-chat', 
    'Coder::deepseek-coder'
    ]
google = [
    'Gemini 1.0 Pro::gemini-1.0-pro-latest'
    ]

[web]
surf_timeout_seconds = 15
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
