[models]
openai = ['gpt-4-turbo-preview', 'gpt-4', 'gpt-3.5-turbo']
anthropic = ['claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307']
mistral = ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest']
deepseek = ['deepseek-chat', 'deepseek-coder']

[web]
surf_timeout_seconds = 15
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
